### ISSUE TITLE
EEPROM Set Device Addrees

### ISSUE THREAD

**Issue by ghost** [per1234/EEPROMutility#1]
How to set custom eeprom device address based on A0, A1 and A2?
Most of the time 0x50 works with commercial vendor eeprom but how to set specific one?

**Comment by per1234** [comment]
Hi @drbsin. This sketch is written for use with the internal EEPROM on the AVR microcontrollers. It doesn't have support for external EEPROM.

For assistance with your external EEPROM, you're welcome to post on [the Arduino Forum](Read http://forum.arduino.cc/index.php?topic=148850).
